/**
 * Pricing Matrix — the CELL-MAP PROFILE.
 *
 * This is the one thing we capture per insurer workbook. It tells the engine (pm_run.py)
 * which cells to WRITE the census into and which cells to READ premiums/totals from, so we
 * can drive the insurer's own Excel formula graph without re-deriving any pricing. AI
 * proposes it from a workbook dump; a human confirms/edits it before the calculator goes live.
 *
 * Column references are spreadsheet COLUMN LETTERS (e.g. "E"); the engine combines them with a
 * per-life ROW from `rows`. Total/global references are ABSOLUTE cells (e.g. "Z118").
 */

/** A single per-life input field mapped to a column on the data sheet. */
export type MemberInputs = {
  name?: string                 // column letter, e.g. "C"
  category?: string             // Employee / Dependent (drives some formulas)
  date_of_birth?: string        // date column — engine converts to Excel serial
  policy_effective_date?: string
  policy_expiry_date?: string
  relationship?: string         // Self / Spouse / Child
  occupation_class?: string     // if it's a per-life (not per-coverage) input
}

/** One coverage line (product) the workbook prices, with its plan-selection inputs + output. */
export type CoverageLine = {
  code: string                  // stable slug, e.g. "HS", "OPGP"
  label: string                 // display, e.g. "Hospital & Surgical"
  inputs: Record<string, string> // field -> column letter, e.g. { plan:"J", hospital:"K", beds:"L", coinsurance:"M" }
  output: string                // premium column letter for this line, e.g. "N"
}

export type CellMapProfile = {
  sheet: string                 // the sheet to drive, e.g. "Calculator"
  rows: { start: number; end: number } // per-life data rows (one member per row)

  member_inputs: MemberInputs
  coverage_lines: CoverageLine[]

  /** Single-cell inputs that apply to the whole quote (not per-life), field -> absolute cell. */
  globals?: Record<string, string> // e.g. { quote_basis: "F5", effective_date: "F4" }

  /** Output totals — absolute cells. by_line keyed by coverage `code`. */
  totals: {
    by_line?: Record<string, string> // { HS:"N116", OPGP:"Q116", ... }
    grand?: string                    // grand total annual premium, e.g. "Z118"
  }

  /** Some workbooks don't expose per-coverage-line premium outputs on the driving sheet — only a
   *  single PER-LIFE TOTAL column (e.g. Income's Step-1 col "Y"). When set, the engine reads this
   *  column as each member's total; the grand total is summed across members if `totals.grand` is
   *  unmapped. Coverage lines are still used for their INPUTS (plan selections). */
  per_life_total?: string             // column letter on `sheet`, e.g. "Y"

  /** Dropdown domains discovered from data-validations, for the review UI + census dropdowns.
   *  Keyed by "field" for member inputs or "CODE.field" for coverage inputs. */
  dropdowns?: Record<string, string[]>

  /** Whether date inputs must be written as Excel serial numbers (almost always true). */
  date_serial?: boolean

  /** If the workbook's total includes GST and we want net premiums, divide computed totals by this
   *  (e.g. 1.09 for SG 9%). Applied by the engine to per-life totals + by_line + grand. */
  total_gst_divisor?: number

  /** Fields the engine could not map / a human left blank — surfaced in the review UI. */
  unmapped?: string[]

  /** A structured, human-readable account of what the AI understood about the workbook — shown as
   *  a sorted breakdown in the review UI (replaces the old free-text `unmapped` blob). */
  analysis?: {
    detected_sheets?: { sheet: string; role: string }[] // role: "census input" | "premiums" | "rate table" | "notes" | ...
    mapped?: string[]        // confirmed mappings, short phrases e.g. "Name → B"
    assumptions?: string[]   // legacy free-text (fallback); prefer review_items
    needs_review?: string[]  // legacy free-text (fallback); prefer review_items
    /** Interactive questions the reviewer answers to settle assumptions + gaps in place. */
    review_items?: ReviewItem[]
  }

  /** Free-text notes the workbook carries (business rules), kept for context/recommendation. */
  notes_text?: string
}

/** One answer option on a review question. Choosing it either edits the profile or dismisses. */
export type ReviewOption = {
  label: string
  set?: { path: string; value: string | number | null } // apply a fixed value to the profile at `path`
  pick_column?: boolean     // reveal a column picker; the chosen column letter is written to the item's target_path
  value_input?: 'number' | 'text' // reveal an input; the entered value is written to target_path
  dismiss?: boolean         // acknowledge only — no change
  recommended?: boolean
}

/** An interactive review question generated by the mapper (assumption to confirm, or a gap to fix). */
export type ReviewItem = {
  id: string
  severity: 'assumption' | 'action'
  question: string
  target_path?: string      // profile path the pick_column / value_input options write to
  options: ReviewOption[]
  resolved?: { label: string; value?: string | number | null } // set once the reviewer answers
}

/** Empty profile scaffold. */
export const EMPTY_PROFILE: CellMapProfile = {
  sheet: '',
  rows: { start: 0, end: 0 },
  member_inputs: {},
  coverage_lines: [],
  totals: {},
  date_serial: true,
}

/** Minimal validity check used to gate "run verification" / "approve".
 *  A profile is runnable when each coverage line has inputs AND premiums are readable — either via
 *  a per-life-total column OR a per-line output on every coverage line. */
export function profileIsRunnable(p: CellMapProfile | null | undefined): boolean {
  if (!p || !p.sheet) return false
  if (!p.rows || !(p.rows.end >= p.rows.start && p.rows.start > 0)) return false
  if (!p.member_inputs?.date_of_birth) return false
  if (!Array.isArray(p.coverage_lines) || p.coverage_lines.length === 0) return false
  const inputsOk = p.coverage_lines.every(l => l.code && l.inputs && Object.keys(l.inputs).length > 0)
  if (!inputsOk) return false
  return !!p.per_life_total || p.coverage_lines.every(l => l.output)
}

// ── Review items (interactive resolve wizard) ────────────────────────────────────
/** The review questions for a profile — the AI's structured items, or (for older calculators that
 *  only have free-text) acknowledge-only items derived from the legacy strings. */
export function deriveReviewItems(p: CellMapProfile | null | undefined): ReviewItem[] {
  const a = p?.analysis
  if (a?.review_items?.length) return a.review_items
  const legacy = [
    ...(a?.needs_review ?? []).map((t, i) => ({ id: `nr-${i}`, severity: 'action' as const, question: t })),
    ...(a?.assumptions ?? []).map((t, i) => ({ id: `as-${i}`, severity: 'assumption' as const, question: t })),
    ...(!a && p?.unmapped ? p.unmapped.map((t, i) => ({ id: `um-${i}`, severity: 'action' as const, question: t })) : []),
  ]
  return legacy.map(it => ({ ...it, options: [{ label: 'Acknowledge', dismiss: true }] }))
}

export function unresolvedReviewCount(p: CellMapProfile | null | undefined): number {
  return deriveReviewItems(p).filter(it => !it.resolved).length
}

/** Apply a review answer to the profile at a dot-path. Returns a new profile (immutable). */
export function applyProfilePath(p: CellMapProfile, path: string, value: string | number | null): CellMapProfile {
  const np: CellMapProfile = { ...p, member_inputs: { ...p.member_inputs }, rows: { ...p.rows } }
  const s = typeof value === 'string' ? value.trim() : value
  if (path === 'rows.start') np.rows.start = Number(s) || 0
  else if (path === 'rows.end') np.rows.end = Number(s) || 0
  else if (path === 'per_life_total') np.per_life_total = s ? String(s).toUpperCase() : undefined
  else if (path === 'total_gst_divisor') np.total_gst_divisor = s ? Number(s) : undefined
  else if (path.startsWith('member_inputs.')) {
    const k = path.slice('member_inputs.'.length) as keyof MemberInputs
    ;(np.member_inputs as Record<string, string | undefined>)[k] = s ? String(s).toUpperCase() : undefined
  }
  return np
}

/** Mark a review item resolved (and store the chosen answer) in the profile. */
export function resolveReviewItem(p: CellMapProfile, id: string, resolved: ReviewItem['resolved']): CellMapProfile {
  const items = deriveReviewItems(p).map(it => it.id === id ? { ...it, resolved } : it)
  return { ...p, analysis: { ...p.analysis, review_items: items } }
}
